### ISSUE TITLE
error: duplicate value for resource 'attr/orientation' 

### ISSUE THREAD

**Issue by Shajeel-Afzal** [csdodd/GradientLayout#5]
I am getting the following error while trying to use the library in my project: 

Error:FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  Output:  PATH_TO_PROJECT/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:817: error: duplicate value for resource 'attr/orientation' with config ''.
  PATH_TO_PROJECT/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:817: error: resource previously defined here.
  
  Command: /Users/shajeelafzal/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.0-alpha16-4748712-osx.jar/ace538feb31c631367cf6256f7814c69/aapt2-3.2.0-alpha16-4748712-osx/aapt2 compile --legacy \
          -o \
          PATH_TO_PROJECT/app/build/intermediates/res/merged/debug \
          PATH_TO_PROJECT/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml
  Daemon:  AAPT2 aapt2-3.2.0-alpha16-4748712-osx Daemon #0
  Output:  /Users/shajeelafzal/.gradle/caches/transforms-1/files-1.1/constraint-layout-1.1.0.aar/07e0ebfd3fa4627aa5ceb077a0ec4b56/res/values/values.xml:130:5-108: AAPT: error: duplicate value for resource 'attr/orientation' with config ''.
      
  /Users/shajeelafzal/.gradle/caches/transforms-1/files-1.1/constraint-layout-1.1.0.aar/07e0ebfd3fa4627aa5ceb077a0ec4b56/res/values/values.xml:130:5-108: AAPT: error: resource previously defined here.
      
  Command: /Users/shajeelafzal/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.0-alpha16-4748712-osx.jar/ace538feb31c631367cf6256f7814c69/aapt2-3.2.0-alpha16-4748712-osx/aapt2 compile --legacy \
          -o \
          PATH_TO_PROJECT/app/build/intermediates/res/merged/debug \
          PATH_TO_PROJECT/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml
  Daemon:  AAPT2 aapt2-3.2.0-alpha16-4748712-osx Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Exception in thread "ForkJoinPool.commonPool-worker-6" java.lang.IllegalStateException: AAPT Process manager cannot be shut down while daemons are in use
	at com.android.builder.internal.aapt.v2.Aapt2DaemonManager.shutdown(Aapt2DaemonManager.kt:96)
	at com.android.build.gradle.internal.res.namespaced.RegisteredAaptService.shutdown(Aapt2DaemonManagerService.kt:61)
	at com.android.build.gradle.internal.workeractions.WorkerActionServiceRegistry$shutdownAllRegisteredServices$1$1.run(WorkerActionServiceRegistry.kt:96)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by HJaliliani** [comment]
> AAPT: error: duplicate value for resource 'attr/orientation' with config ''.

Did you find any solution, @Shajeel-Afzal ?

**Comment by HJaliliani** [comment]
For me it was the solution, I  hope also  working for you  :
https://stackoverflow.com/questions/53895569/error-duplicate-value-for-resource-attr-orientation-with-config-aapt-v2-a/53895653#53895653
